### ISSUE TITLE
Fitting Analyzer crashes on kqxhc

### ISSUE THREAD

**Issue by tking53** [pixie16/paass#177]
Using the gsl1 fitting analyzer for ornl2016 data causes a crash on Kqxhc, after 18631 words

`gsl: ../gsl/gsl_vector_double.h:177: ERROR: index out of range`
is the error, and 

```
Program received signal SIGABRT, Aborted.
0x0000003477432625 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install freetype-2.3.11-6.el6_2.9.x86_64 glibc-2.12-1.166.el6_7.3.x86_64 gsl-1.13-1.el6.x86_64 keyutils-libs-1.4-4.el6.x86_64 krb5-libs-1.9-33.el6_3.3.x86_64 libcom_err-1.41.12-12.el6.x86_64 libgcc-4.4.7-17.el6.x86_64 libselinux-2.0.94-5.3.el6.x86_64 libstdc++-4.4.7-17.el6.x86_64 ncurses-libs-5.7-3.20090208.el6.x86_64 nss-mdns-0.10-8.el6.x86_64 openssl-1.0.1e-16.el6_5.7.x86_64 pcre-7.8-4.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x0000003477432625 in raise () from /lib64/libc.so.6
#1  0x0000003477433e05 in abort () from /lib64/libc.so.6
#2  0x000000361747233b in gsl_error () from /usr/lib64/libgsl.so.0
#3  0x00000036175849e5 in gsl_vector_get () from /usr/lib64/libgsl.so.0
#4  0x00000000004f8957 in GslFitter::CalculatePhase(std::vector<double, std::allocator<double> > const&, std::pair<double, double> const&, std::pair<unsigned int, double> const&, std::pair<double, double>) ()
#5  0x00000000004a0719 in FittingAnalyzer::Analyze(Trace&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > > const&) ()
#6  0x000000000043b90b in DetectorDriver::ThreshAndCal(ChanEvent*, RawEvent&) ()
#7  0x000000000043d659 in DetectorDriver::ProcessEvent(RawEvent&) ()
#8  0x000000000045daf2 in UtkUnpacker::ProcessRawEvent(ScanInterface*) ()
#9  0x00000000004f1b91 in Unpacker::ReadSpill(unsigned int*, unsigned int, bool) ()
#10 0x00000000004ea1e5 in ScanInterface::RunControl() ()
#11 0x00000000004ec128 in ScanInterface::Execute() ()
#12 0x00000000004292be in main ()
```

is the gdb backtrace

**Comment by spaulaus** [comment]
I am going to close this issue, since kqxhc is going to be upgraded and this information will no longer be valid.
