### ISSUE TITLE
Utkscanor does not parse command line arguments properly

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#246]
# Description
Utkscanor does not parse command line arguments properly. The command line arguments are interpreted from FORTRAN instead of standard C++, which means that there's additional function calls necessary to get these parameters into the c++ section of the software. The offender that provides the error is the `--frequency` flag. 

The scan provides the following output:
```
> utkscanor.cpp : Instancing the UtkScanInterface
utkscan.cpp : Setting the Program Name
utkscan.cpp : Performing the setup routine
terminate called after throwing an instance of 'std::invalid_argument'
  what():  ScanInterface::Setup - The frequency has not been set.

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7fe421fd70af in ???
#1  0x7fe421fd704f in ???
#2  0x7fe421fd8479 in ???
#3  0x7fe4225ea4ec in _ZN9__gnu_cxx27__verbose_terminate_handlerEv
	at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#4  0x7fe4225e82a5 in _ZN10__cxxabiv111__terminateEPFvvE
	at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#5  0x7fe4225e82f0 in _ZSt9terminatev
	at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#6  0x7fe4225e8507 in __cxa_throw
	at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:87
#7  0x5a0192 in _ZN13ScanInterface5SetupEiPPc
	at /home/vincent/programs/sources/utk/paass/Analysis/ScanLibraries/source/ScanInterface.cpp:979
#8  0x4dd503 in startup_
	at /home/vincent/programs/sources/utk/paass/Analysis/Utkscan/core/source/utkscanor.cpp:33
#9  0x57b3a7 in MAIN__
	at /home/vincent/programs/sources/utk/paass/Analysis/Scanor/source/scanor.f:90
#10  0x57c50e in main
	at /home/vincent/programs/sources/utk/paass/Analysis/Scanor/source/scanor.f:320
```

# Work to be Done
1. Figure out why the arguments are not being parsed properly
2. Confirm what arguments are having issues.
2. Fix the issue
3. Profit

# Acceptance Criteria
1. The code compiles
2. All command line arguments are parsed properly.

**Comment by spaulaus** [comment]
User Error.....
