### ISSUE TITLE
Segmentation Fault in batch mode

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#71]
98bdc81186ca5dc7e73c4472e0a2bb8efb413f50 introduced a segmentation fault when using batch mode. 

Stack Trace:

```
#6  0x0000000000515940 in Terminal::ClearStatus(unsigned short) ()
#7  0x0000000000515a23 in Terminal::SetStatus(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned short) ()
#8  0x00000000004f7095 in ScanInterface::stop_scan() ()
#9  0x00000000004ff46c in ScanInterface::RunControl() ()
#10 0x0000000000502bc8 in ScanInterface::Execute() ()
#11 0x000000000042484a in main ()
```

**Comment by ksmith0** [comment]
Resolved in commit dadd2895314b047aa876ad334993ab2a6f256441
